### ISSUE TITLE
notes, todolists 404 error

### ISSUE THREAD

**Issue by amamov** [iflag/webfrontend#3]

**Comment by numeru** [comment]
저는 pc, 모바일 모두 정상적으로 가져와지는데 혹시 오류코드나 관련된걸 볼 수 있을까요?

**Comment by amamov** [comment]
원인 찾았습니다! 백엔드 수정했습니다 :)

2021년 7월 11일 (일) 오후 10:13, numeru ***@***.***>님이 작성:
