### ISSUE TITLE
favicon api

### ISSUE THREAD

**Issue by numeru** [iflag/webfrontend#5]
Mixed Content:
The page at 'https://iflag.co/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://favicongrabber.com/api/grab/www.pinterest.co.kr'.
This request has been blocked; the content must be served over HTTPS.

http라서 favicon api가 안되는 것 같아요. 다른 api를 찾아볼까요?

**Comment by amamov** [comment]
넵 아니면 그냥 직접 구현해보죠! 수요일에 회의합시다!
